### ISSUE TITLE
Could not install from "../../../ruddell/Contrib/ignite-jhipster"

### ISSUE THREAD

**Issue by jraleman** [ruddell/IgniteJhipsterSampleApp#1]
I get the following error when I: 
- `git clone`
- `npm install`

```
Could not install from "../../../ruddell/Contrib/ignite-jhipster" as it does not contain a package.json file.
```

I fixed it removing `line 73` from `package.json`:

```
73.    "ignite-jhipster": "file:/Users/ruddell/Contrib/ignite-jhipster",
```

**Comment by ruddell** [comment]
This is just a sample app. You should use ignite-jhipster to generate your own app

You can work around this by setting the ignite-jhipster version to the latest number

**Comment by jraleman** [comment]
Ohhh, got it!
Thanks :)
