### ISSUE TITLE
Reset screen when I go home then back 

### ISSUE THREAD

**Issue by quyenbc** [ruddell/IgniteJhipsterSampleApp#2]
Hi there,
I tried the app on my android phone. 
I opened register screen and entered some data. Then i pressed home key, and back to the app, all data i entered before lost.

**Comment by ruddell** [comment]
Thanks for reporting the issue. 👍   I opened a new issue in the `ignite-jhipster` repository where the actual code resides https://github.com/ruddell/ignite-jhipster/issues/45
